name: Release snapshot version

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

on:
    push:
        branches: [main]

jobs:
    release-new-version:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Allow us to create a release
            packages: write # Publish the package

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build and run tests
              run: ./gradlew test

            - name: Publish packages
              run: >
                  ./gradlew publishAllPublicationsToSnapshotsRepository \
                    -PsnapshotsUsername=${{ secrets.reposilite_user }} \
                    -PsnapshotsPassword=${{ secrets.reposilite_password }} \
                    -Pversion=1.0.0-SNAPSHOT
