name: Release

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

on:
    workflow_dispatch:
        inputs:
            version:
                description: New Version to Release
                required: true
                type: string

jobs:
    release-new-version:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Allow us to create a release
            packages: write # Publish the package

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build and run tests
              run: ./gradlew test

            - name: Publish packages
              run: >
                  ./gradlew publishAllPublicationsToReleasesRepository \
                    -PreposiliteRepositoryUsername=${{ secrets.reposilite_user }} \
                    -PreposiliteRepositoryPassword=${{ secrets.reposilite_password }} \
                    -Pversion=${{ inputs.version }}


            - name: Create Release on GitHub
              run: gh release create --generate-notes ${{ inputs.version }}
              env:
                  GH_TOKEN: ${{ github.token }}
